#!/usr/bin/env python3
"""Pipeline: Markdown → JSON → DOCX.

Orchestrates md_to_json.py and render_docx.py (must exist in the same directory
as this script, generated by the docx-deterministic-generator skill).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
FIX_TABLES = SCRIPT_DIR / "fix_md_tables.py"
MD_TO_JSON = SCRIPT_DIR / "md_to_json.py"
RENDER_DOCX = SCRIPT_DIR / "render_docx.py"


def check_scripts() -> None:
    missing = []
    if not MD_TO_JSON.exists():
        missing.append(f"  - {MD_TO_JSON}")
    if not RENDER_DOCX.exists():
        missing.append(f"  - {RENDER_DOCX}")
    if missing:
        print("错误：缺少以下脚本文件：", file=sys.stderr)
        for line in missing:
            print(line, file=sys.stderr)
        print("", file=sys.stderr)
        print("请先使用 docx-deterministic-generator skill 分析 .docx 模板，", file=sys.stderr)
        print("生成 md_to_json.py 和 render_docx.py，然后复制到：", file=sys.stderr)
        print(f"  {SCRIPT_DIR}/", file=sys.stderr)
        sys.exit(1)


def run_step(step: int, total: int, description: str, cmd: list[str]) -> None:
    print(f"[{step}/{total}] {description}")
    print(f"  运行：{' '.join(cmd)}")
    result = subprocess.run(cmd)
    if result.returncode != 0:
        print(f"\n错误：{description} 失败（退出码 {result.returncode}）", file=sys.stderr)
        sys.exit(result.returncode)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--md", required=True, type=Path, help="输入的 Markdown 文档")
    parser.add_argument("--template", required=True, type=Path, help=".docx 模板文件")
    parser.add_argument("--output", required=True, type=Path, help="输出 .docx 路径")
    parser.add_argument("--keep-json", action="store_true", help="保留中间 JSON 文件")
    args = parser.parse_args()

    for path, label in [
        (args.md, "Markdown 文件"),
        (args.template, ".docx 模板"),
    ]:
        if not path.exists():
            print(f"错误：{label}不存在：{path}", file=sys.stderr)
            sys.exit(1)

    check_scripts()

    args.output.parent.mkdir(parents=True, exist_ok=True)

    # 预处理：修复非矩形管道表格
    tmp_md = tempfile.NamedTemporaryFile(suffix=".md", delete=False, dir=args.output.parent)
    fixed_md_path = Path(tmp_md.name)
    tmp_md.close()

    if args.keep_json:
        json_path = args.output.with_suffix(".json")
    else:
        tmp = tempfile.NamedTemporaryFile(suffix=".json", delete=False, dir=args.output.parent)
        json_path = Path(tmp.name)
        tmp.close()

    try:
        run_step(
            1, 3, "修复非矩形表格",
            [
                sys.executable, str(FIX_TABLES),
                "--input", str(args.md),
                "--output", str(fixed_md_path),
            ],
        )

        run_step(
            2, 3, "Markdown → JSON",
            [
                sys.executable, str(MD_TO_JSON),
                "--input", str(fixed_md_path),
                "--output", str(json_path),
            ],
        )

        run_step(
            3, 3, "JSON → DOCX",
            [
                sys.executable, str(RENDER_DOCX),
                "--template", str(args.template),
                "--input", str(json_path),
                "--output", str(args.output),
                "--base-dir", str(args.md.parent),
            ],
        )

        print(f"\n完成：{args.output}")
    finally:
        if fixed_md_path.exists():
            fixed_md_path.unlink()
        if not args.keep_json and json_path.exists():
            json_path.unlink()


if __name__ == "__main__":
    main()
